apiVersion: v1
kind: Service
metadata:
  name: udagram-api-users-app
  labels:
    run: udagram-api-users-app
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: udagram-api-users-app
