apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-app
  labels:
    run: udagram-api-feed-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-api-feed-app
