apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed-app
  labels:
    app: udagram-api-feed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed-app
  template:
    metadata:
      labels:
        app: udagram-api-feed-app
    spec:
      containers:
      - name: udagram-api-feed
        image: alexgarcia2k/udagram-api-feed
        ports:
        - containerPort: 8080
